// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: booking.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBooking = `-- name: CreateBooking :one
INSERT INTO booking (userId, trainId, travelDate, status, holdToken)
VALUES ($1, $2, $3, 'PENDING', $4)
RETURNING id, userid, trainid, traveldate, status, holdtoken, paymentid, createdat
`

type CreateBookingParams struct {
	Userid     pgtype.UUID `json:"userid"`
	Trainid    pgtype.Int4 `json:"trainid"`
	Traveldate pgtype.Date `json:"traveldate"`
	Holdtoken  pgtype.Text `json:"holdtoken"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.Userid,
		arg.Trainid,
		arg.Traveldate,
		arg.Holdtoken,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.Trainid,
		&i.Traveldate,
		&i.Status,
		&i.Holdtoken,
		&i.Paymentid,
		&i.Createdat,
	)
	return i, err
}

const createBookingItem = `-- name: CreateBookingItem :one
INSERT INTO bookingItem (bookingId, seatId, trainScheduleId)
VALUES ($1, $2, $3)
RETURNING id, bookingid, seatid, trainscheduleid
`

type CreateBookingItemParams struct {
	Bookingid       pgtype.Int4 `json:"bookingid"`
	Seatid          pgtype.Int4 `json:"seatid"`
	Trainscheduleid pgtype.Int4 `json:"trainscheduleid"`
}

func (q *Queries) CreateBookingItem(ctx context.Context, arg CreateBookingItemParams) (Bookingitem, error) {
	row := q.db.QueryRow(ctx, createBookingItem, arg.Bookingid, arg.Seatid, arg.Trainscheduleid)
	var i Bookingitem
	err := row.Scan(
		&i.ID,
		&i.Bookingid,
		&i.Seatid,
		&i.Trainscheduleid,
	)
	return i, err
}

const getBookedSeats = `-- name: GetBookedSeats :many
SELECT bi.seatId
FROM bookingItem bi
JOIN booking b on bi.bookingId = b.id
 WHERE b.trainId = $1 AND
  b.travelDate = $2
  AND b.status IN('PENDING','CONFIRMED')
`

type GetBookedSeatsParams struct {
	Trainid    pgtype.Int4 `json:"trainid"`
	Traveldate pgtype.Date `json:"traveldate"`
}

func (q *Queries) GetBookedSeats(ctx context.Context, arg GetBookedSeatsParams) ([]pgtype.Int4, error) {
	rows, err := q.db.Query(ctx, getBookedSeats, arg.Trainid, arg.Traveldate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Int4{}
	for rows.Next() {
		var seatid pgtype.Int4
		if err := rows.Scan(&seatid); err != nil {
			return nil, err
		}
		items = append(items, seatid)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookingByHoldToken = `-- name: GetBookingByHoldToken :one
SELECT id, userid, trainid, traveldate, status, holdtoken, paymentid, createdat FROM booking WHERE holdToken = $1
`

func (q *Queries) GetBookingByHoldToken(ctx context.Context, holdtoken pgtype.Text) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingByHoldToken, holdtoken)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.Trainid,
		&i.Traveldate,
		&i.Status,
		&i.Holdtoken,
		&i.Paymentid,
		&i.Createdat,
	)
	return i, err
}

const getBookingbyUserId = `-- name: GetBookingbyUserId :many
SELECT bi.id, bi.bookingid, bi.seatid, bi.trainscheduleid , b.id, b.userid, b.trainid, b.traveldate, b.status, b.holdtoken, b.paymentid, b.createdat
FROM booking b 
JOIN bookingItem bi 
ON b.id = bi.bookingId
WHERE b.userId = $1
`

type GetBookingbyUserIdRow struct {
	ID              int32            `json:"id"`
	Bookingid       pgtype.Int4      `json:"bookingid"`
	Seatid          pgtype.Int4      `json:"seatid"`
	Trainscheduleid pgtype.Int4      `json:"trainscheduleid"`
	ID_2            int32            `json:"id_2"`
	Userid          pgtype.UUID      `json:"userid"`
	Trainid         pgtype.Int4      `json:"trainid"`
	Traveldate      pgtype.Date      `json:"traveldate"`
	Status          BookingStatus    `json:"status"`
	Holdtoken       pgtype.Text      `json:"holdtoken"`
	Paymentid       pgtype.Int4      `json:"paymentid"`
	Createdat       pgtype.Timestamp `json:"createdat"`
}

func (q *Queries) GetBookingbyUserId(ctx context.Context, userid pgtype.UUID) ([]GetBookingbyUserIdRow, error) {
	rows, err := q.db.Query(ctx, getBookingbyUserId, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBookingbyUserIdRow{}
	for rows.Next() {
		var i GetBookingbyUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.Bookingid,
			&i.Seatid,
			&i.Trainscheduleid,
			&i.ID_2,
			&i.Userid,
			&i.Trainid,
			&i.Traveldate,
			&i.Status,
			&i.Holdtoken,
			&i.Paymentid,
			&i.Createdat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBookingStatus = `-- name: UpdateBookingStatus :exec
UPDATE booking
SET status = $2
WHERE id = $1
`

type UpdateBookingStatusParams struct {
	ID     int32         `json:"id"`
	Status BookingStatus `json:"status"`
}

func (q *Queries) UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) error {
	_, err := q.db.Exec(ctx, updateBookingStatus, arg.ID, arg.Status)
	return err
}
