// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: booking.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveBookingByTrain = `-- name: CountActiveBookingByTrain :one
SELECT COUNT(*)
FROM booking
WHERE journey_id = $1
  AND status = 'PENDING'
`

func (q *Queries) CountActiveBookingByTrain(ctx context.Context, journeyID pgtype.Int4) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveBookingByTrain, journeyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO booking (userId, journey_id, booking_type, status, holdToken)
VALUES ($1, $2, 'NORMAL', 'PENDING', $3)
RETURNING id, userid, journey_id, booking_type, status, holdtoken, createdat
`

type CreateBookingParams struct {
	Userid    pgtype.UUID `json:"userid"`
	JourneyID pgtype.Int4 `json:"journey_id"`
	Holdtoken pgtype.Text `json:"holdtoken"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking, arg.Userid, arg.JourneyID, arg.Holdtoken)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.JourneyID,
		&i.BookingType,
		&i.Status,
		&i.Holdtoken,
		&i.Createdat,
	)
	return i, err
}

const createBookingItem = `-- name: CreateBookingItem :one
INSERT INTO bookingItem (bookingId, seatId)
VALUES ($1, $2)
RETURNING id, bookingid, seatid, bookingstatus
`

type CreateBookingItemParams struct {
	Bookingid pgtype.Int4 `json:"bookingid"`
	Seatid    pgtype.Int4 `json:"seatid"`
}

func (q *Queries) CreateBookingItem(ctx context.Context, arg CreateBookingItemParams) (Bookingitem, error) {
	row := q.db.QueryRow(ctx, createBookingItem, arg.Bookingid, arg.Seatid)
	var i Bookingitem
	err := row.Scan(
		&i.ID,
		&i.Bookingid,
		&i.Seatid,
		&i.Bookingstatus,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one
 INSERT into payment (bookingId,amount,transactionId)
 VALUES($1,$2,$3)
 RETURNING id, bookingid, amount, status, transactionid, createdat
`

type CreatePaymentParams struct {
	Bookingid     pgtype.Int4 `json:"bookingid"`
	Amount        float64     `json:"amount"`
	Transactionid string      `json:"transactionid"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment, arg.Bookingid, arg.Amount, arg.Transactionid)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.Bookingid,
		&i.Amount,
		&i.Status,
		&i.Transactionid,
		&i.Createdat,
	)
	return i, err
}

const currentAvailableSeats = `-- name: CurrentAvailableSeats :many
SELECT seat_id
FROM seat_inventory
WHERE journey_id = $1
  AND status = 'AVAILABLE'
  AND seat_id = ANY($2::int[])
`

type CurrentAvailableSeatsParams struct {
	JourneyID int32   `json:"journey_id"`
	Column2   []int32 `json:"column_2"`
}

func (q *Queries) CurrentAvailableSeats(ctx context.Context, arg CurrentAvailableSeatsParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, currentAvailableSeats, arg.JourneyID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var seat_id int32
		if err := rows.Scan(&seat_id); err != nil {
			return nil, err
		}
		items = append(items, seat_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteBookingItem = `-- name: DeleteBookingItem :exec
DELETE FROM
bookingItem b WHERE bookingId = $1
`

func (q *Queries) DeleteBookingItem(ctx context.Context, bookingid pgtype.Int4) error {
	_, err := q.db.Exec(ctx, deleteBookingItem, bookingid)
	return err
}

const deleteBookingItemsByBooking = `-- name: DeleteBookingItemsByBooking :exec
DELETE FROM bookingItem WHERE bookingId = $1
`

func (q *Queries) DeleteBookingItemsByBooking(ctx context.Context, bookingid pgtype.Int4) error {
	_, err := q.db.Exec(ctx, deleteBookingItemsByBooking, bookingid)
	return err
}

const expireOldBooking = `-- name: ExpireOldBooking :exec
UPDATE booking
SET status='EXPIRED'
 WHERE status='PENDING'
   AND createdat < now() - INTERVAL '10 minutes'
`

func (q *Queries) ExpireOldBooking(ctx context.Context) error {
	_, err := q.db.Exec(ctx, expireOldBooking)
	return err
}

const getActiveBookingByUser = `-- name: GetActiveBookingByUser :one
SELECT id, userid, journey_id, booking_type, status, holdtoken, createdat
FROM booking
WHERE userid = $1
  AND status = 'PENDING'
  AND createdAt > now() - INTERVAL '10 minutes'
ORDER BY createdAt DESC
LIMIT 1
`

func (q *Queries) GetActiveBookingByUser(ctx context.Context, userid pgtype.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, getActiveBookingByUser, userid)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.JourneyID,
		&i.BookingType,
		&i.Status,
		&i.Holdtoken,
		&i.Createdat,
	)
	return i, err
}

const getBookedSeats = `-- name: GetBookedSeats :many
SELECT si.seat_id
FROM seat_inventory si
JOIN booking b ON si.booking_id = b.id
WHERE b.journey_id = $1
  AND si.status IN ('HELD','CONFIRMED')
`

func (q *Queries) GetBookedSeats(ctx context.Context, journeyID pgtype.Int4) ([]int32, error) {
	rows, err := q.db.Query(ctx, getBookedSeats, journeyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var seat_id int32
		if err := rows.Scan(&seat_id); err != nil {
			return nil, err
		}
		items = append(items, seat_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookingByHoldToken = `-- name: GetBookingByHoldToken :one
SELECT id, userid, journey_id, booking_type, status, holdtoken, createdat FROM booking WHERE holdToken = $1
`

func (q *Queries) GetBookingByHoldToken(ctx context.Context, holdtoken pgtype.Text) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingByHoldToken, holdtoken)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.JourneyID,
		&i.BookingType,
		&i.Status,
		&i.Holdtoken,
		&i.Createdat,
	)
	return i, err
}

const getBookingById = `-- name: GetBookingById :one
SELECT id, userid, journey_id, booking_type, status, holdtoken, createdat from booking
where id = $1
`

func (q *Queries) GetBookingById(ctx context.Context, id int32) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingById, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.JourneyID,
		&i.BookingType,
		&i.Status,
		&i.Holdtoken,
		&i.Createdat,
	)
	return i, err
}

const getBookingItemsByBooking = `-- name: GetBookingItemsByBooking :many
SELECT seatId FROM bookingItem WHERE bookingId = $1
`

func (q *Queries) GetBookingItemsByBooking(ctx context.Context, bookingid pgtype.Int4) ([]pgtype.Int4, error) {
	rows, err := q.db.Query(ctx, getBookingItemsByBooking, bookingid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Int4{}
	for rows.Next() {
		var seatid pgtype.Int4
		if err := rows.Scan(&seatid); err != nil {
			return nil, err
		}
		items = append(items, seatid)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookingLockContext = `-- name: GetBookingLockContext :many
SELECT
    b.journey_id,
    si.seat_id,
    b.holdToken
FROM booking b
JOIN seat_inventory si ON si.booking_id = b.id
WHERE b.id = $1
`

type GetBookingLockContextRow struct {
	JourneyID pgtype.Int4 `json:"journey_id"`
	SeatID    int32       `json:"seat_id"`
	Holdtoken pgtype.Text `json:"holdtoken"`
}

func (q *Queries) GetBookingLockContext(ctx context.Context, id int32) ([]GetBookingLockContextRow, error) {
	rows, err := q.db.Query(ctx, getBookingLockContext, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBookingLockContextRow{}
	for rows.Next() {
		var i GetBookingLockContextRow
		if err := rows.Scan(&i.JourneyID, &i.SeatID, &i.Holdtoken); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookingbyUserId = `-- name: GetBookingbyUserId :many
SELECT bi.id, bi.bookingid, bi.seatid, bi.bookingstatus , b.id, b.userid, b.journey_id, b.booking_type, b.status, b.holdtoken, b.createdat
FROM booking b 
JOIN bookingItem bi 
ON b.id = bi.bookingId
WHERE b.userId = $1
`

type GetBookingbyUserIdRow struct {
	ID            int32            `json:"id"`
	Bookingid     pgtype.Int4      `json:"bookingid"`
	Seatid        pgtype.Int4      `json:"seatid"`
	Bookingstatus BookingStatus    `json:"bookingstatus"`
	ID_2          int32            `json:"id_2"`
	Userid        pgtype.UUID      `json:"userid"`
	JourneyID     pgtype.Int4      `json:"journey_id"`
	BookingType   BookingType      `json:"booking_type"`
	Status        BookingStatus    `json:"status"`
	Holdtoken     pgtype.Text      `json:"holdtoken"`
	Createdat     pgtype.Timestamp `json:"createdat"`
}

func (q *Queries) GetBookingbyUserId(ctx context.Context, userid pgtype.UUID) ([]GetBookingbyUserIdRow, error) {
	rows, err := q.db.Query(ctx, getBookingbyUserId, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBookingbyUserIdRow{}
	for rows.Next() {
		var i GetBookingbyUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.Bookingid,
			&i.Seatid,
			&i.Bookingstatus,
			&i.ID_2,
			&i.Userid,
			&i.JourneyID,
			&i.BookingType,
			&i.Status,
			&i.Holdtoken,
			&i.Createdat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBookingItemStatus = `-- name: UpdateBookingItemStatus :exec
UPDATE bookingItem SET bookingStatus = $2 WHERE bookingId = $1
`

type UpdateBookingItemStatusParams struct {
	Bookingid     pgtype.Int4   `json:"bookingid"`
	Bookingstatus BookingStatus `json:"bookingstatus"`
}

func (q *Queries) UpdateBookingItemStatus(ctx context.Context, arg UpdateBookingItemStatusParams) error {
	_, err := q.db.Exec(ctx, updateBookingItemStatus, arg.Bookingid, arg.Bookingstatus)
	return err
}

const updateBookingStatus = `-- name: UpdateBookingStatus :exec
UPDATE booking
SET status = $2
WHERE id = $1
`

type UpdateBookingStatusParams struct {
	ID     int32         `json:"id"`
	Status BookingStatus `json:"status"`
}

func (q *Queries) UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) error {
	_, err := q.db.Exec(ctx, updateBookingStatus, arg.ID, arg.Status)
	return err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :exec
UPDATE payment SET status = $2 WHERE bookingId = $1
`

type UpdatePaymentStatusParams struct {
	Bookingid pgtype.Int4       `json:"bookingid"`
	Status    NullPaymentStatus `json:"status"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error {
	_, err := q.db.Exec(ctx, updatePaymentStatus, arg.Bookingid, arg.Status)
	return err
}
