// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cancellation.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPaymentAndTrain = `-- name: GetPaymentAndTrain :one
SELECT p.amount,p.status as payment_status,b.travelDate , b.holdToken , b.status as booking_status FROM
booking b JOIN
payment p ON b.id = p.bookingId
WHERE b.trainId = $2 AND b.userId = $1 AND b.travelDate = $3
LIMIT 1
`

type GetPaymentAndTrainParams struct {
	Userid     pgtype.UUID `json:"userid"`
	Trainid    pgtype.Int4 `json:"trainid"`
	Traveldate pgtype.Date `json:"traveldate"`
}

type GetPaymentAndTrainRow struct {
	Amount        float64           `json:"amount"`
	PaymentStatus NullPaymentStatus `json:"payment_status"`
	Traveldate    pgtype.Date       `json:"traveldate"`
	Holdtoken     pgtype.Text       `json:"holdtoken"`
	BookingStatus BookingStatus     `json:"booking_status"`
}

func (q *Queries) GetPaymentAndTrain(ctx context.Context, arg GetPaymentAndTrainParams) (GetPaymentAndTrainRow, error) {
	row := q.db.QueryRow(ctx, getPaymentAndTrain, arg.Userid, arg.Trainid, arg.Traveldate)
	var i GetPaymentAndTrainRow
	err := row.Scan(
		&i.Amount,
		&i.PaymentStatus,
		&i.Traveldate,
		&i.Holdtoken,
		&i.BookingStatus,
	)
	return i, err
}
