// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cancellation.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefund = `-- name: CreateRefund :one
INSERT INTO refund (userId , bookingId , amount , status , createdAt, updatedAt) 
VALUES ( $1 , $2 , $3 , $4 , now() , now() )
RETURNING id, userid, bookingid, amount, status, createdat, updatedat
`

type CreateRefundParams struct {
	Userid    pgtype.UUID  `json:"userid"`
	Bookingid pgtype.Int4  `json:"bookingid"`
	Amount    int32        `json:"amount"`
	Status    RefundStatus `json:"status"`
}

func (q *Queries) CreateRefund(ctx context.Context, arg CreateRefundParams) (Refund, error) {
	row := q.db.QueryRow(ctx, createRefund,
		arg.Userid,
		arg.Bookingid,
		arg.Amount,
		arg.Status,
	)
	var i Refund
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.Bookingid,
		&i.Amount,
		&i.Status,
		&i.Createdat,
		&i.Updatedat,
	)
	return i, err
}

const getPaymentAndTrain = `-- name: GetPaymentAndTrain :one
SELECT b.id, b.userid, b.journey_id, b.booking_type, b.status, b.holdtoken, b.createdat , p.id, p.bookingid, p.amount, p.status, p.transactionid, p.createdat
FROM
booking b JOIN
payment p ON b.id = p.bookingId
WHERE b.journey_id = $2 AND b.userId = $1 AND p.status = 'SUCCESS'
`

type GetPaymentAndTrainParams struct {
	Userid    pgtype.UUID `json:"userid"`
	JourneyID pgtype.Int4 `json:"journey_id"`
}

type GetPaymentAndTrainRow struct {
	ID            int32             `json:"id"`
	Userid        pgtype.UUID       `json:"userid"`
	JourneyID     pgtype.Int4       `json:"journey_id"`
	BookingType   BookingType       `json:"booking_type"`
	Status        BookingStatus     `json:"status"`
	Holdtoken     pgtype.Text       `json:"holdtoken"`
	Createdat     pgtype.Timestamp  `json:"createdat"`
	ID_2          int32             `json:"id_2"`
	Bookingid     pgtype.Int4       `json:"bookingid"`
	Amount        float64           `json:"amount"`
	Status_2      NullPaymentStatus `json:"status_2"`
	Transactionid string            `json:"transactionid"`
	Createdat_2   pgtype.Timestamp  `json:"createdat_2"`
}

func (q *Queries) GetPaymentAndTrain(ctx context.Context, arg GetPaymentAndTrainParams) (GetPaymentAndTrainRow, error) {
	row := q.db.QueryRow(ctx, getPaymentAndTrain, arg.Userid, arg.JourneyID)
	var i GetPaymentAndTrainRow
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.JourneyID,
		&i.BookingType,
		&i.Status,
		&i.Holdtoken,
		&i.Createdat,
		&i.ID_2,
		&i.Bookingid,
		&i.Amount,
		&i.Status_2,
		&i.Transactionid,
		&i.Createdat_2,
	)
	return i, err
}
