// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BerthType string

const (
	BerthTypeUP   BerthType = "UP"
	BerthTypeDOWN BerthType = "DOWN"
	BerthTypeMID  BerthType = "MID"
)

func (e *BerthType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BerthType(s)
	case string:
		*e = BerthType(s)
	default:
		return fmt.Errorf("unsupported scan type for BerthType: %T", src)
	}
	return nil
}

type NullBerthType struct {
	BerthType BerthType `json:"berth_type"`
	Valid     bool      `json:"valid"` // Valid is true if BerthType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBerthType) Scan(value interface{}) error {
	if value == nil {
		ns.BerthType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BerthType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBerthType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BerthType), nil
}

type BookingStatus string

const (
	BookingStatusPENDING   BookingStatus = "PENDING"
	BookingStatusCONFIRMED BookingStatus = "CONFIRMED"
	BookingStatusCANCELLED BookingStatus = "CANCELLED"
	BookingStatusEXPIRED   BookingStatus = "EXPIRED"
)

func (e *BookingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BookingStatus(s)
	case string:
		*e = BookingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BookingStatus: %T", src)
	}
	return nil
}

type NullBookingStatus struct {
	BookingStatus BookingStatus `json:"booking_status"`
	Valid         bool          `json:"valid"` // Valid is true if BookingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBookingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BookingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BookingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBookingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BookingStatus), nil
}

type CoachType string

const (
	CoachType3A CoachType = "3A"
	CoachType2A CoachType = "2A"
	CoachType1A CoachType = "1A"
	CoachTypeSL CoachType = "SL"
	CoachTypeGN CoachType = "GN"
)

func (e *CoachType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CoachType(s)
	case string:
		*e = CoachType(s)
	default:
		return fmt.Errorf("unsupported scan type for CoachType: %T", src)
	}
	return nil
}

type NullCoachType struct {
	CoachType CoachType `json:"coach_type"`
	Valid     bool      `json:"valid"` // Valid is true if CoachType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCoachType) Scan(value interface{}) error {
	if value == nil {
		ns.CoachType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CoachType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCoachType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CoachType), nil
}

type DayOfWeek string

const (
	DayOfWeekMON DayOfWeek = "MON"
	DayOfWeekTUE DayOfWeek = "TUE"
	DayOfWeekWED DayOfWeek = "WED"
	DayOfWeekTHU DayOfWeek = "THU"
	DayOfWeekFRI DayOfWeek = "FRI"
	DayOfWeekSAT DayOfWeek = "SAT"
	DayOfWeekSUN DayOfWeek = "SUN"
)

func (e *DayOfWeek) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DayOfWeek(s)
	case string:
		*e = DayOfWeek(s)
	default:
		return fmt.Errorf("unsupported scan type for DayOfWeek: %T", src)
	}
	return nil
}

type NullDayOfWeek struct {
	DayOfWeek DayOfWeek `json:"day_of_week"`
	Valid     bool      `json:"valid"` // Valid is true if DayOfWeek is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDayOfWeek) Scan(value interface{}) error {
	if value == nil {
		ns.DayOfWeek, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DayOfWeek.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDayOfWeek) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DayOfWeek), nil
}

type PaymentStatus string

const (
	PaymentStatusPENDING PaymentStatus = "PENDING"
	PaymentStatusFAILED  PaymentStatus = "FAILED"
	PaymentStatusSUCCESS PaymentStatus = "SUCCESS"
)

func (e *PaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatus(s)
	case string:
		*e = PaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatus: %T", src)
	}
	return nil
}

type NullPaymentStatus struct {
	PaymentStatus PaymentStatus `json:"payment_status"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatus), nil
}

type Provider string

const (
	ProviderEMAIL    Provider = "EMAIL"
	ProviderAPPLE    Provider = "APPLE"
	ProviderPASSWORD Provider = "PASSWORD"
)

func (e *Provider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Provider(s)
	case string:
		*e = Provider(s)
	default:
		return fmt.Errorf("unsupported scan type for Provider: %T", src)
	}
	return nil
}

type NullProvider struct {
	Provider Provider `json:"provider"`
	Valid    bool     `json:"valid"` // Valid is true if Provider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProvider) Scan(value interface{}) error {
	if value == nil {
		ns.Provider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Provider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Provider), nil
}

type UserRole string

const (
	UserRoleADMIN UserRole = "ADMIN"
	UserRoleUSER  UserRole = "USER"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Booking struct {
	ID         int32            `json:"id"`
	Userid     pgtype.UUID      `json:"userid"`
	Trainid    pgtype.Int4      `json:"trainid"`
	Traveldate pgtype.Date      `json:"traveldate"`
	Status     BookingStatus    `json:"status"`
	Holdtoken  pgtype.Text      `json:"holdtoken"`
	Paymentid  pgtype.Int4      `json:"paymentid"`
	Createdat  pgtype.Timestamp `json:"createdat"`
}

type Bookingitem struct {
	ID              int32       `json:"id"`
	Bookingid       pgtype.Int4 `json:"bookingid"`
	Seatid          pgtype.Int4 `json:"seatid"`
	Trainscheduleid pgtype.Int4 `json:"trainscheduleid"`
}

type Coach struct {
	ID          int32       `json:"id"`
	Trainid     pgtype.Int4 `json:"trainid"`
	Coachtype   CoachType   `json:"coachtype"`
	Coachnumber int32       `json:"coachnumber"`
}

type Payment struct {
	ID            int32             `json:"id"`
	Bookingid     pgtype.Int4       `json:"bookingid"`
	Amount        float64           `json:"amount"`
	Status        NullPaymentStatus `json:"status"`
	Transactionid string            `json:"transactionid"`
	Createdat     pgtype.Timestamp  `json:"createdat"`
}

type Seat struct {
	ID      int32       `json:"id"`
	Coachid pgtype.Int4 `json:"coachid"`
	Seatno  int32       `json:"seatno"`
	Berth   BerthType   `json:"berth"`
}

type Tatkal struct {
	ID         int32       `json:"id"`
	Trainid    pgtype.Int4 `json:"trainid"`
	Coachtype  CoachType   `json:"coachtype"`
	Totalseats pgtype.Int4 `json:"totalseats"`
}

type Train struct {
	ID          int32  `json:"id"`
	Trainnumber int32  `json:"trainnumber"`
	Trainname   string `json:"trainname"`
	Source      string `json:"source"`
	Destination string `json:"destination"`
}

type Trainschedule struct {
	ID            int32       `json:"id"`
	Trainid       pgtype.Int4 `json:"trainid"`
	Day           DayOfWeek   `json:"day"`
	Arrivaltime   time.Time   `json:"arrivaltime"`
	Departuretime time.Time   `json:"departuretime"`
}

type User struct {
	ID           uuid.UUID        `json:"id"`
	Fullname     string           `json:"fullname"`
	Email        string           `json:"email"`
	Role         UserRole         `json:"role"`
	PasswordHash pgtype.Text      `json:"password_hash"`
	Provider     Provider         `json:"provider"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	Phone        pgtype.Text      `json:"phone"`
}
