// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BerthType string

const (
	BerthTypeUP   BerthType = "UP"
	BerthTypeDOWN BerthType = "DOWN"
	BerthTypeMID  BerthType = "MID"
)

func (e *BerthType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BerthType(s)
	case string:
		*e = BerthType(s)
	default:
		return fmt.Errorf("unsupported scan type for BerthType: %T", src)
	}
	return nil
}

type NullBerthType struct {
	BerthType BerthType `json:"berth_type"`
	Valid     bool      `json:"valid"` // Valid is true if BerthType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBerthType) Scan(value interface{}) error {
	if value == nil {
		ns.BerthType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BerthType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBerthType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BerthType), nil
}

type BookingStatus string

const (
	BookingStatusPENDING   BookingStatus = "PENDING"
	BookingStatusCONFIRMED BookingStatus = "CONFIRMED"
	BookingStatusWAITLIST  BookingStatus = "WAITLIST"
	BookingStatusCANCELLED BookingStatus = "CANCELLED"
	BookingStatusEXPIRED   BookingStatus = "EXPIRED"
)

func (e *BookingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BookingStatus(s)
	case string:
		*e = BookingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BookingStatus: %T", src)
	}
	return nil
}

type NullBookingStatus struct {
	BookingStatus BookingStatus `json:"booking_status"`
	Valid         bool          `json:"valid"` // Valid is true if BookingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBookingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BookingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BookingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBookingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BookingStatus), nil
}

type BookingType string

const (
	BookingTypeNORMAL   BookingType = "NORMAL"
	BookingTypeWAITLIST BookingType = "WAITLIST"
	BookingTypeTATKAL   BookingType = "TATKAL"
)

func (e *BookingType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BookingType(s)
	case string:
		*e = BookingType(s)
	default:
		return fmt.Errorf("unsupported scan type for BookingType: %T", src)
	}
	return nil
}

type NullBookingType struct {
	BookingType BookingType `json:"booking_type"`
	Valid       bool        `json:"valid"` // Valid is true if BookingType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBookingType) Scan(value interface{}) error {
	if value == nil {
		ns.BookingType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BookingType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBookingType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BookingType), nil
}

type CoachType string

const (
	CoachType3A CoachType = "3A"
	CoachType2A CoachType = "2A"
	CoachType1A CoachType = "1A"
	CoachTypeSL CoachType = "SL"
	CoachTypeGN CoachType = "GN"
)

func (e *CoachType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CoachType(s)
	case string:
		*e = CoachType(s)
	default:
		return fmt.Errorf("unsupported scan type for CoachType: %T", src)
	}
	return nil
}

type NullCoachType struct {
	CoachType CoachType `json:"coach_type"`
	Valid     bool      `json:"valid"` // Valid is true if CoachType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCoachType) Scan(value interface{}) error {
	if value == nil {
		ns.CoachType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CoachType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCoachType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CoachType), nil
}

type DayOfWeek string

const (
	DayOfWeekMON DayOfWeek = "MON"
	DayOfWeekTUE DayOfWeek = "TUE"
	DayOfWeekWED DayOfWeek = "WED"
	DayOfWeekTHU DayOfWeek = "THU"
	DayOfWeekFRI DayOfWeek = "FRI"
	DayOfWeekSAT DayOfWeek = "SAT"
	DayOfWeekSUN DayOfWeek = "SUN"
)

func (e *DayOfWeek) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DayOfWeek(s)
	case string:
		*e = DayOfWeek(s)
	default:
		return fmt.Errorf("unsupported scan type for DayOfWeek: %T", src)
	}
	return nil
}

type NullDayOfWeek struct {
	DayOfWeek DayOfWeek `json:"day_of_week"`
	Valid     bool      `json:"valid"` // Valid is true if DayOfWeek is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDayOfWeek) Scan(value interface{}) error {
	if value == nil {
		ns.DayOfWeek, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DayOfWeek.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDayOfWeek) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DayOfWeek), nil
}

type PaymentStatus string

const (
	PaymentStatusPENDING PaymentStatus = "PENDING"
	PaymentStatusFAILED  PaymentStatus = "FAILED"
	PaymentStatusSUCCESS PaymentStatus = "SUCCESS"
)

func (e *PaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatus(s)
	case string:
		*e = PaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatus: %T", src)
	}
	return nil
}

type NullPaymentStatus struct {
	PaymentStatus PaymentStatus `json:"payment_status"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatus), nil
}

type Provider string

const (
	ProviderEMAIL    Provider = "EMAIL"
	ProviderAPPLE    Provider = "APPLE"
	ProviderPASSWORD Provider = "PASSWORD"
)

func (e *Provider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Provider(s)
	case string:
		*e = Provider(s)
	default:
		return fmt.Errorf("unsupported scan type for Provider: %T", src)
	}
	return nil
}

type NullProvider struct {
	Provider Provider `json:"provider"`
	Valid    bool     `json:"valid"` // Valid is true if Provider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProvider) Scan(value interface{}) error {
	if value == nil {
		ns.Provider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Provider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Provider), nil
}

type RefundStatus string

const (
	RefundStatusPENDING RefundStatus = "PENDING"
	RefundStatusFAILED  RefundStatus = "FAILED"
	RefundStatusSUCCESS RefundStatus = "SUCCESS"
)

func (e *RefundStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RefundStatus(s)
	case string:
		*e = RefundStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RefundStatus: %T", src)
	}
	return nil
}

type NullRefundStatus struct {
	RefundStatus RefundStatus `json:"refund_status"`
	Valid        bool         `json:"valid"` // Valid is true if RefundStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRefundStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RefundStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RefundStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRefundStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RefundStatus), nil
}

type UserRole string

const (
	UserRoleADMIN UserRole = "ADMIN"
	UserRoleUSER  UserRole = "USER"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type WaitingStatus string

const (
	WaitingStatusWAITING   WaitingStatus = "WAITING"
	WaitingStatusCONFIRMED WaitingStatus = "CONFIRMED"
	WaitingStatusCANCELLED WaitingStatus = "CANCELLED"
)

func (e *WaitingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WaitingStatus(s)
	case string:
		*e = WaitingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WaitingStatus: %T", src)
	}
	return nil
}

type NullWaitingStatus struct {
	WaitingStatus WaitingStatus `json:"waiting_status"`
	Valid         bool          `json:"valid"` // Valid is true if WaitingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWaitingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WaitingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WaitingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWaitingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WaitingStatus), nil
}

type Booking struct {
	ID          int32            `json:"id"`
	Userid      pgtype.UUID      `json:"userid"`
	Trainid     pgtype.Int4      `json:"trainid"`
	Traveldate  pgtype.Date      `json:"traveldate"`
	Status      BookingStatus    `json:"status"`
	Holdtoken   pgtype.Text      `json:"holdtoken"`
	Paymentid   pgtype.Int4      `json:"paymentid"`
	Createdat   pgtype.Timestamp `json:"createdat"`
	BookingType pgtype.Text      `json:"booking_type"`
}

type Bookingitem struct {
	ID              int32         `json:"id"`
	Bookingid       pgtype.Int4   `json:"bookingid"`
	Seatid          pgtype.Int4   `json:"seatid"`
	Bookingstatus   BookingStatus `json:"bookingstatus"`
	Trainscheduleid pgtype.Int4   `json:"trainscheduleid"`
}

type Coach struct {
	ID          int32       `json:"id"`
	Trainid     pgtype.Int4 `json:"trainid"`
	Coachtype   CoachType   `json:"coachtype"`
	Coachnumber int32       `json:"coachnumber"`
}

type Passenger struct {
	ID            int32            `json:"id"`
	Name          string           `json:"name"`
	Bookingitemid pgtype.Int4      `json:"bookingitemid"`
	Age           int32            `json:"age"`
	Createdat     pgtype.Timestamp `json:"createdat"`
}

type Payment struct {
	ID            int32             `json:"id"`
	Bookingid     pgtype.Int4       `json:"bookingid"`
	Amount        float64           `json:"amount"`
	Status        NullPaymentStatus `json:"status"`
	Transactionid string            `json:"transactionid"`
	Createdat     pgtype.Timestamp  `json:"createdat"`
}

type Refund struct {
	ID        int32            `json:"id"`
	Userid    pgtype.UUID      `json:"userid"`
	Bookingid pgtype.Int4      `json:"bookingid"`
	Amount    int32            `json:"amount"`
	Status    RefundStatus     `json:"status"`
	Createdat pgtype.Timestamp `json:"createdat"`
	Updatedat pgtype.Timestamp `json:"updatedat"`
}

type Seat struct {
	ID      int32       `json:"id"`
	Coachid pgtype.Int4 `json:"coachid"`
	Seatno  int32       `json:"seatno"`
	Berth   BerthType   `json:"berth"`
}

type TatkalConfig struct {
	ID              int32            `json:"id"`
	TrainID         pgtype.Int4      `json:"train_id"`
	Coachtype       CoachType        `json:"coachtype"`
	TatkalStartTime pgtype.Timestamp `json:"tatkal_start_time"`
	TatkalEndTime   pgtype.Timestamp `json:"tatkal_end_time"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type TatkalWaitlist struct {
	ID         int32            `json:"id"`
	UserID     uuid.UUID        `json:"user_id"`
	TrainID    pgtype.Int4      `json:"train_id"`
	CoachType  CoachType        `json:"coach_type"`
	TravelDate pgtype.Date      `json:"travel_date"`
	WlPosition int32            `json:"wl_position"`
	Status     pgtype.Text      `json:"status"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type Train struct {
	ID          int32  `json:"id"`
	Trainnumber int32  `json:"trainnumber"`
	Trainname   string `json:"trainname"`
	Source      string `json:"source"`
	Destination string `json:"destination"`
}

type Trainschedule struct {
	ID            int32       `json:"id"`
	Trainid       pgtype.Int4 `json:"trainid"`
	Day           DayOfWeek   `json:"day"`
	Arrivaltime   time.Time   `json:"arrivaltime"`
	Departuretime time.Time   `json:"departuretime"`
}

type User struct {
	ID           uuid.UUID        `json:"id"`
	Fullname     string           `json:"fullname"`
	Email        string           `json:"email"`
	Role         UserRole         `json:"role"`
	PasswordHash pgtype.Text      `json:"password_hash"`
	Provider     Provider         `json:"provider"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	Phone        pgtype.Text      `json:"phone"`
}

type Waitlist struct {
	ID              int32            `json:"id"`
	Trainscheduleid pgtype.Int4      `json:"trainscheduleid"`
	Bookingid       pgtype.Int4      `json:"bookingid"`
	WaitlistNumber  int32            `json:"waitlist_number"`
	Status          WaitingStatus    `json:"status"`
	PriorityLevel   pgtype.Int4      `json:"priority_level"`
	Createdat       pgtype.Timestamp `json:"createdat"`
	Updatedat       pgtype.Timestamp `json:"updatedat"`
}
