// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tatkal.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const validateTatkalWindow = `-- name: ValidateTatkalWindow :one
SELECT id, train_id, coach_type, tatkal_start_time, tatkal_end_time, created_at, updated_at from 
tatkal_config
where train_id = $1
`

func (q *Queries) ValidateTatkalWindow(ctx context.Context, trainID pgtype.Int4) (TatkalConfig, error) {
	row := q.db.QueryRow(ctx, validateTatkalWindow, trainID)
	var i TatkalConfig
	err := row.Scan(
		&i.ID,
		&i.TrainID,
		&i.CoachType,
		&i.TatkalStartTime,
		&i.TatkalEndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
