// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: train.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const confirmSeat = `-- name: ConfirmSeat :exec
UPDATE seat_inventory
SET status = 'CONFIRMED'
WHERE booking_id = $1
AND status = 'HELD'
`

func (q *Queries) ConfirmSeat(ctx context.Context, bookingID pgtype.Int4) error {
	_, err := q.db.Exec(ctx, confirmSeat, bookingID)
	return err
}

const createCoach = `-- name: CreateCoach :one
INSERT into coach (trainId,coachtype,coachNumber) VALUES ($1 , $2 , $3) RETURNING id, trainid, coachtype, coachnumber
`

type CreateCoachParams struct {
	Trainid     pgtype.Int4 `json:"trainid"`
	Coachtype   CoachType   `json:"coachtype"`
	Coachnumber int32       `json:"coachnumber"`
}

func (q *Queries) CreateCoach(ctx context.Context, arg CreateCoachParams) (Coach, error) {
	row := q.db.QueryRow(ctx, createCoach, arg.Trainid, arg.Coachtype, arg.Coachnumber)
	var i Coach
	err := row.Scan(
		&i.ID,
		&i.Trainid,
		&i.Coachtype,
		&i.Coachnumber,
	)
	return i, err
}

const createSeat = `-- name: CreateSeat :one
INSERT into seat (coachId,seatno,berth) VALUES ($1 , $2 , $3) RETURNING id, coachid, seatno, berth
`

type CreateSeatParams struct {
	Coachid pgtype.Int4 `json:"coachid"`
	Seatno  int32       `json:"seatno"`
	Berth   BerthType   `json:"berth"`
}

func (q *Queries) CreateSeat(ctx context.Context, arg CreateSeatParams) (Seat, error) {
	row := q.db.QueryRow(ctx, createSeat, arg.Coachid, arg.Seatno, arg.Berth)
	var i Seat
	err := row.Scan(
		&i.ID,
		&i.Coachid,
		&i.Seatno,
		&i.Berth,
	)
	return i, err
}

const createTrain = `-- name: CreateTrain :one
INSERT into train(trainNumber,trainName,source,destination )
VALUES ( $1 ,$2 ,$3,$4) 
RETURNING id, trainnumber, trainname, source, destination
`

type CreateTrainParams struct {
	Trainnumber int32  `json:"trainnumber"`
	Trainname   string `json:"trainname"`
	Source      string `json:"source"`
	Destination string `json:"destination"`
}

func (q *Queries) CreateTrain(ctx context.Context, arg CreateTrainParams) (Train, error) {
	row := q.db.QueryRow(ctx, createTrain,
		arg.Trainnumber,
		arg.Trainname,
		arg.Source,
		arg.Destination,
	)
	var i Train
	err := row.Scan(
		&i.ID,
		&i.Trainnumber,
		&i.Trainname,
		&i.Source,
		&i.Destination,
	)
	return i, err
}

const createTrainJourney = `-- name: CreateTrainJourney :one
INSERT INTO train_journey (train_id , journey_date ,schedule_id, status )
VALUES( $1 , $2 , $3 , $4) RETURNING id, train_id, journey_date, schedule_id, status, created_at
`

type CreateTrainJourneyParams struct {
	TrainID     pgtype.Int4       `json:"train_id"`
	JourneyDate pgtype.Date       `json:"journey_date"`
	ScheduleID  pgtype.Int4       `json:"schedule_id"`
	Status      NullJourneyStatus `json:"status"`
}

func (q *Queries) CreateTrainJourney(ctx context.Context, arg CreateTrainJourneyParams) (TrainJourney, error) {
	row := q.db.QueryRow(ctx, createTrainJourney,
		arg.TrainID,
		arg.JourneyDate,
		arg.ScheduleID,
		arg.Status,
	)
	var i TrainJourney
	err := row.Scan(
		&i.ID,
		&i.TrainID,
		&i.JourneyDate,
		&i.ScheduleID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createTrainSchedule = `-- name: CreateTrainSchedule :one
INSERT into train_schedule (trainId,day,arrivalTime,departureTime)
VALUES ( $1 ,$2 ,$3,$4) 
RETURNING id, trainid, day, arrivaltime, departuretime
`

type CreateTrainScheduleParams struct {
	Trainid       pgtype.Int4 `json:"trainid"`
	Day           DayOfWeek   `json:"day"`
	Arrivaltime   pgtype.Time `json:"arrivaltime"`
	Departuretime pgtype.Time `json:"departuretime"`
}

func (q *Queries) CreateTrainSchedule(ctx context.Context, arg CreateTrainScheduleParams) (TrainSchedule, error) {
	row := q.db.QueryRow(ctx, createTrainSchedule,
		arg.Trainid,
		arg.Day,
		arg.Arrivaltime,
		arg.Departuretime,
	)
	var i TrainSchedule
	err := row.Scan(
		&i.ID,
		&i.Trainid,
		&i.Day,
		&i.Arrivaltime,
		&i.Departuretime,
	)
	return i, err
}

const getAllTrain = `-- name: GetAllTrain :many
SELECT t.id, t.trainnumber, t.trainname, t.source, t.destination , ts.id, ts.trainid, ts.day, ts.arrivaltime, ts.departuretime
FROM train t
JOIN train_schedule ts ON t.id = ts.trainid
`

type GetAllTrainRow struct {
	ID            int32       `json:"id"`
	Trainnumber   int32       `json:"trainnumber"`
	Trainname     string      `json:"trainname"`
	Source        string      `json:"source"`
	Destination   string      `json:"destination"`
	ID_2          int32       `json:"id_2"`
	Trainid       pgtype.Int4 `json:"trainid"`
	Day           DayOfWeek   `json:"day"`
	Arrivaltime   pgtype.Time `json:"arrivaltime"`
	Departuretime pgtype.Time `json:"departuretime"`
}

func (q *Queries) GetAllTrain(ctx context.Context) ([]GetAllTrainRow, error) {
	rows, err := q.db.Query(ctx, getAllTrain)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllTrainRow{}
	for rows.Next() {
		var i GetAllTrainRow
		if err := rows.Scan(
			&i.ID,
			&i.Trainnumber,
			&i.Trainname,
			&i.Source,
			&i.Destination,
			&i.ID_2,
			&i.Trainid,
			&i.Day,
			&i.Arrivaltime,
			&i.Departuretime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAvailableSeats = `-- name: GetAvailableSeats :many
SELECT
    si.coach_type,
    COUNT(*) FILTER (WHERE si.status = 'AVAILABLE') AS available_seats,
    COUNT(*) FILTER (WHERE si.status = 'CONFIRMED') AS booked_seats,
    COUNT(*) AS total_seats
FROM seat_inventory si
JOIN train_journey tj ON tj.id = si.journey_id
WHERE tj.train_id = $1
  AND tj.journey_date = $2
  AND si.quota = $3
GROUP BY si.coach_type
ORDER BY si.coach_type
`

type GetAvailableSeatsParams struct {
	TrainID     pgtype.Int4 `json:"train_id"`
	JourneyDate pgtype.Date `json:"journey_date"`
	Quota       SeatQuota   `json:"quota"`
}

type GetAvailableSeatsRow struct {
	CoachType      CoachType `json:"coach_type"`
	AvailableSeats int64     `json:"available_seats"`
	BookedSeats    int64     `json:"booked_seats"`
	TotalSeats     int64     `json:"total_seats"`
}

func (q *Queries) GetAvailableSeats(ctx context.Context, arg GetAvailableSeatsParams) ([]GetAvailableSeatsRow, error) {
	rows, err := q.db.Query(ctx, getAvailableSeats, arg.TrainID, arg.JourneyDate, arg.Quota)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAvailableSeatsRow{}
	for rows.Next() {
		var i GetAvailableSeatsRow
		if err := rows.Scan(
			&i.CoachType,
			&i.AvailableSeats,
			&i.BookedSeats,
			&i.TotalSeats,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoachesByTrain = `-- name: GetCoachesByTrain :many
SELECT id, trainid, coachtype, coachnumber FROM coach WHERE trainId = $1
`

func (q *Queries) GetCoachesByTrain(ctx context.Context, trainid pgtype.Int4) ([]Coach, error) {
	rows, err := q.db.Query(ctx, getCoachesByTrain, trainid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Coach{}
	for rows.Next() {
		var i Coach
		if err := rows.Scan(
			&i.ID,
			&i.Trainid,
			&i.Coachtype,
			&i.Coachnumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNextCoachNumber = `-- name: GetNextCoachNumber :one
SELECT COALESCE(MAX(coachNumber), 0) + 1
FROM coach
WHERE trainId = $1
FOR UPDATE
`

func (q *Queries) GetNextCoachNumber(ctx context.Context, trainid pgtype.Int4) (int, error) {
	row := q.db.QueryRow(ctx, getNextCoachNumber, trainid)
	var column_1 int
	err := row.Scan(&column_1)
	return column_1, err
}

const getSeatsByCoach = `-- name: GetSeatsByCoach :many
SELECT id, coachid, seatno, berth FROM seat WHERE coachId = $1
`

func (q *Queries) GetSeatsByCoach(ctx context.Context, coachid pgtype.Int4) ([]Seat, error) {
	rows, err := q.db.Query(ctx, getSeatsByCoach, coachid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Seat{}
	for rows.Next() {
		var i Seat
		if err := rows.Scan(
			&i.ID,
			&i.Coachid,
			&i.Seatno,
			&i.Berth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeatsByTrain = `-- name: GetSeatsByTrain :many
SELECT s.id, s.coachid, s.seatno, s.berth
FROM seat s 
JOIN coach c ON s.coachId = c.id
WHERE c.trainId = $1
`

func (q *Queries) GetSeatsByTrain(ctx context.Context, trainid pgtype.Int4) ([]Seat, error) {
	rows, err := q.db.Query(ctx, getSeatsByTrain, trainid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Seat{}
	for rows.Next() {
		var i Seat
		if err := rows.Scan(
			&i.ID,
			&i.Coachid,
			&i.Seatno,
			&i.Berth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrainById = `-- name: GetTrainById :one
SELECT id, trainnumber, trainname, source, destination FROM train
WHERE id = $1
`

func (q *Queries) GetTrainById(ctx context.Context, id int32) (Train, error) {
	row := q.db.QueryRow(ctx, getTrainById, id)
	var i Train
	err := row.Scan(
		&i.ID,
		&i.Trainnumber,
		&i.Trainname,
		&i.Source,
		&i.Destination,
	)
	return i, err
}

const getTrainScheduleByDay = `-- name: GetTrainScheduleByDay :one
SELECT id, trainid, day, arrivaltime, departuretime
FROM train_schedule
WHERE trainId = $1
AND day = $2
`

type GetTrainScheduleByDayParams struct {
	Trainid pgtype.Int4 `json:"trainid"`
	Day     DayOfWeek   `json:"day"`
}

func (q *Queries) GetTrainScheduleByDay(ctx context.Context, arg GetTrainScheduleByDayParams) (TrainSchedule, error) {
	row := q.db.QueryRow(ctx, getTrainScheduleByDay, arg.Trainid, arg.Day)
	var i TrainSchedule
	err := row.Scan(
		&i.ID,
		&i.Trainid,
		&i.Day,
		&i.Arrivaltime,
		&i.Departuretime,
	)
	return i, err
}

const holdSeat = `-- name: HoldSeat :exec

UPDATE seat_inventory
SET status = 'HELD',
    booking_id = $3
WHERE journey_id = $1
  AND seat_id = $2
  AND status = 'AVAILABLE'
`

type HoldSeatParams struct {
	JourneyID int32       `json:"journey_id"`
	SeatID    int32       `json:"seat_id"`
	BookingID pgtype.Int4 `json:"booking_id"`
}

// below are not applied till now
func (q *Queries) HoldSeat(ctx context.Context, arg HoldSeatParams) error {
	_, err := q.db.Exec(ctx, holdSeat, arg.JourneyID, arg.SeatID, arg.BookingID)
	return err
}

const lockTrainForLayout = `-- name: LockTrainForLayout :one
SELECT id
FROM train
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockTrainForLayout(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, lockTrainForLayout, id)
	err := row.Scan(&id)
	return id, err
}

const releaseExpiredSeats = `-- name: ReleaseExpiredSeats :exec
UPDATE seat_inventory
SET status = 'AVAILABLE',
    booking_id = NULL
WHERE status = 'HELD'
AND booking_id IN (
    SELECT id FROM booking
    WHERE status = 'PENDING'
    AND createdAt < now() - interval '5 minutes'
)
`

func (q *Queries) ReleaseExpiredSeats(ctx context.Context) error {
	_, err := q.db.Exec(ctx, releaseExpiredSeats)
	return err
}

const validateSchedule = `-- name: ValidateSchedule :one
SELECT COUNT(*)
FROM train_schedule
WHERE trainId = $1
AND day = $2
`

type ValidateScheduleParams struct {
	Trainid pgtype.Int4 `json:"trainid"`
	Day     DayOfWeek   `json:"day"`
}

func (q *Queries) ValidateSchedule(ctx context.Context, arg ValidateScheduleParams) (int64, error) {
	row := q.db.QueryRow(ctx, validateSchedule, arg.Trainid, arg.Day)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const validateSeatsBelongToTrain = `-- name: ValidateSeatsBelongToTrain :one
SELECT COUNT(*) = $1::int as all_seat_belong,
 count(*)::int as seat_found,
 $1 - COUNT(*) as seats_not_found
 FROM seat s 
 JOIN coach c on s.coachId = c.id
 WHERE s.id = ANY($2::int[])
  AND c.trainId = $3
`

type ValidateSeatsBelongToTrainParams struct {
	Column1 int32       `json:"column_1"`
	Column2 []int32     `json:"column_2"`
	Trainid pgtype.Int4 `json:"trainid"`
}

type ValidateSeatsBelongToTrainRow struct {
	AllSeatBelong bool  `json:"all_seat_belong"`
	SeatFound     int32 `json:"seat_found"`
	SeatsNotFound int   `json:"seats_not_found"`
}

func (q *Queries) ValidateSeatsBelongToTrain(ctx context.Context, arg ValidateSeatsBelongToTrainParams) (ValidateSeatsBelongToTrainRow, error) {
	row := q.db.QueryRow(ctx, validateSeatsBelongToTrain, arg.Column1, arg.Column2, arg.Trainid)
	var i ValidateSeatsBelongToTrainRow
	err := row.Scan(&i.AllSeatBelong, &i.SeatFound, &i.SeatsNotFound)
	return i, err
}

const validateTrain = `-- name: ValidateTrain :one

SELECT COUNT(*)
FROM train WHERE id = $1
`

// SELECT *
// FROM get_available_seats(1, '2026-01-15');
func (q *Queries) ValidateTrain(ctx context.Context, id int32) (int64, error) {
	row := q.db.QueryRow(ctx, validateTrain, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}
