// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: waitlist.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getNextWaitlistNumber = `-- name: GetNextWaitlistNumber :one
select COALESCE(MAX(waitlist_number), 0) + 1
from waitlist
WHERE journey_id = $1
FOR UPDATE
`

func (q *Queries) GetNextWaitlistNumber(ctx context.Context, journeyID pgtype.Int4) (int, error) {
	row := q.db.QueryRow(ctx, getNextWaitlistNumber, journeyID)
	var column_1 int
	err := row.Scan(&column_1)
	return column_1, err
}

const insertWaitlist = `-- name: InsertWaitlist :exec
INSERT INTO waitlist (
  journey_id,
  bookingId,
  waitlist_number,
  status
)
VALUES ($1, $2, $3, 'WAITING')
`

type InsertWaitlistParams struct {
	JourneyID      pgtype.Int4 `json:"journey_id"`
	Bookingid      pgtype.Int4 `json:"bookingid"`
	WaitlistNumber int32       `json:"waitlist_number"`
}

func (q *Queries) InsertWaitlist(ctx context.Context, arg InsertWaitlistParams) error {
	_, err := q.db.Exec(ctx, insertWaitlist, arg.JourneyID, arg.Bookingid, arg.WaitlistNumber)
	return err
}
